version: "3.9"
services:
  worker:
    build: .
    environment:
      REDIS_URI: $REDIS_URI
      REDIS_PASSWORD: $REDIS_PASSWORD
      SESSION: $SESSION
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      OWNER_ID: $OWNER_ID  # defaults to None
      AUTH_CHANNEL: $AUTH_CHANNEL  # defaults to None
      TG_BOT_TOKEN : $TG_BOT_TOKEN 
      CHUNK_SIZE : $CHUNK_SIZE
      EDIT_SLEEP_TIME_OUT : $EDIT_SLEEP_TIME_OUT
      ARIA_TWO_STARTED_PORT : $ARIA_TWO_STARTED_PORT
      ENV : $ENV




