version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      OWNER_ID: $OWNER_ID  # defaults to None
      AUTH_CHANNEL: $AUTH_CHANNEL  # defaults to None
      TG_BOT_TOKEN : $TG_BOT_TOKEN 




